#!/usr/bin/env bash
# Shared environment for the HCU GLM-5.3-Flash FP8 recipes.
set -eo pipefail

export PYTHONPATH="${PYTHONPATH:-/home/work/code/sglang-das/python}"
export MODEL_PATH="${MODEL_PATH:-/home/work/GLM-5.3-Flash-Channel-FP8-w8a8}"
export PREFILL_HOST="${PREFILL_HOST:-10.6.14.14}"
export PREFILL_PORT="${PREFILL_PORT:-8080}"
export DECODE_HOST="${DECODE_HOST:-10.6.14.15}"
export DECODE_PORT="${DECODE_PORT:-8080}"
export ROUTER_PORT="${ROUTER_PORT:-30005}"

export SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
export SGLANG_DISAGGREGATION_WAITING_TIMEOUT=1200
export SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT=1200
export SGLANG_DISAGGREGATION_TRANSFER_TIMEOUT=1200
export ROCSHMEM_TOPO_FILE_FORCE="${ROCSHMEM_TOPO_FILE_FORCE:-/home/work/deepseekv4/topo.config}"

# Keep the device/network settings from the remote reference environment.  Set
# them in the shell before sourcing this file when a host uses different HCAs.
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
export ROCR_VISIBLE_DEVICES="${ROCR_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-enp113s0f0np0}"
export GLOO_SOCKET_IFNAME="${GLOO_SOCKET_IFNAME:-enp113s0f0np0}"
export NCCL_IB_HCA="${NCCL_IB_HCA:-mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_8:1,mlx5_9:1}"
export ROCSHMEM_ALLOWED_IBV_DEVICES="${ROCSHMEM_ALLOWED_IBV_DEVICES:-mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_8,mlx5_9}"
export MC_ALLOWED_IBV_DEVICES="${MC_ALLOWED_IBV_DEVICES:-mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_8,mlx5_9}"
export ROCSHMEM_IB_GID_INDEX="${ROCSHMEM_IB_GID_INDEX:-0}"
unset NCCL_TOPO_FILE RCCL_TOPO_FILE

export NCCL_MIN_NCHANNELS=16
export NCCL_MAX_NCHANNELS=16
export HSA_ENABLE_COREDUMP=1
export USE_DCU_CUSTOM_ALLREDUCE=0
export SGLANG_USE_AITER_AR=0
export SGLANG_CUSTOM_ALLREDUCE_INPUT_FENCE=thread0
export ALLREDUCE_STREAM_WITH_COMPUTE=1
export HIP_KERNEL_EVENT_SYSTENFENCE=1
export SGLANG_CHUNKED_PREFIX_CACHE_THRESHOLD=0
export GLIBC_TUNABLES=glibc.rtld.optional_static_tls=0x40000
export HIP_KERNEL_BATCH_CEILING=100
export GPU_FORCE_BLIT_COPY_SIZE=16
export HSA_KERNARG_POOL_SIZE=8388608
export ROC_AQL_QUEUE_SIZE=131072
export SGLANG_USE_LIGHTOP=1
export SGLANG_ROCM_USE_AITER_MOE=0
export SGLANG_KVALLOC_KERNEL=1
export SGLANG_CREATE_EXTEND_AFTER_DECODE_SPEC_INFO=1
export SGLANG_ASSIGN_EXTEND_CACHE_LOCS=1
export SGLANG_ASSIGN_REQ_TO_TOKEN_POOL=1
export SGLANG_GET_LAST_LOC=1
export SGLANG_CREATE_FLASHMLA_KV_INDICES_TRITON=1
export SGLANG_CREATE_CHUNKED_PREFIX_CACHE_KV_INDICES=1
export HIP_GRAPH_ACCUMULATE_DISPATCH=1
export HIP_GRAPH_USE_CMD_CACHE=0
export SGLANG_ROCM_USE_AITER_TILELANG_MHC=1
export SGLANG_OPT_USE_TILELANG_MHC_PRE=1
export SGLANG_OPT_USE_TILELANG_MHC_POST=1
export SGLANG_OPT_DEEPGEMM_HC_PRENORM=0
export SGLANG_OPT_SWIGLU_CLAMP_FUSION=0
export ROCSHMEM_GDA_NUM_QPS_DEFAULT_CTX=288
export ROCSHMEM_MAX_NUM_CONTEXTS=60
export ROCSHMEM_HEAP_SIZE=3173741824
export SGLANG_USE_DEEPGEMM_MOE=1
export SGLANG_INT8_DEEPGEMM_ASM=1
export SGLANG_ENABLE_HEALTH_ENDPOINT_GENERATION=1
export W8A8_SUPPORT_METHODS=3
export SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
export SGLANG_USE_AITER_CHUNK_GATED_DELTA_H_HIP=1
export SGLANG_USE_FUSED_RMS_QUANT=1
export SGLANG_USE_FUSED_SILU_MUL_QUANT=1
export SGLANG_USE_LIGHTOP_PREFILL_DEQUANT=1
export SGLANG_USE_FUSED_SILU_MUL_CLAMP_QUANT=1
export SGLANG_USE_HICACHE_OPTIMIZATION_KERNEL=1
export MC_ENABLE_DEST_DEVICE_AFFINITY=1
export GLM_ENABLE_ENCODER_SESSION_ID_HEADER=1
export SGLANG_HTTP_WORKER_REUSE_PORT=1
export TOKENIZERS_PARALLELISM=false
export OMP_NUM_THREADS=1
export RAYON_NUM_THREADS=1
